//
//  MHFDefines+Namespace.h
//  MHFoundation
//
//  Generated using MHNamespaceGenerator on 19/09/2017
//

#if !defined(__MHFOUNDATION_NAMESPACE_APPLY) && defined(MHFOUNDATION_NAMESPACE) && defined(MHFOUNDATION_NAMESPACE_LOWER)
    #define __MHFOUNDATION_NAMESPACE_REWRITE(ns, s) ns ## _ ## s
    #define __MHFOUNDATION_NAMESPACE_BRIDGE(ns, s) __MHFOUNDATION_NAMESPACE_REWRITE(ns, s)
    #define __MHFOUNDATION_NAMESPACE_APPLY(s) __MHFOUNDATION_NAMESPACE_BRIDGE(MHFOUNDATION_NAMESPACE, s)
	#define __MHFOUNDATION_NAMESPACE_APPLY_LOWER(s) __MHFOUNDATION_NAMESPACE_BRIDGE(MHFOUNDATION_NAMESPACE_LOWER, s)
// Classes
    #define MHFAsyncOperation __MHFOUNDATION_NAMESPACE_APPLY(MHFAsyncOperation)
    #define MHFBatchRESTOperation __MHFOUNDATION_NAMESPACE_APPLY(MHFBatchRESTOperation)
    #define MHFError __MHFOUNDATION_NAMESPACE_APPLY(MHFError)
    #define MHFHTTPError __MHFOUNDATION_NAMESPACE_APPLY(MHFHTTPError)
    #define MHFQueueOperation __MHFOUNDATION_NAMESPACE_APPLY(MHFQueueOperation)
    #define MHFRESTOperation __MHFOUNDATION_NAMESPACE_APPLY(MHFRESTOperation)
    #define MHFRunLoopOperation __MHFOUNDATION_NAMESPACE_APPLY(MHFRunLoopOperation)
    #define MHFSerialQueueOperation __MHFOUNDATION_NAMESPACE_APPLY(MHFSerialQueueOperation)
    #define MHFURLSessionAllowInvalidSSLDelegate __MHFOUNDATION_NAMESPACE_APPLY(MHFURLSessionAllowInvalidSSLDelegate)
    #define MHFURLSessionDataTaskOperation __MHFOUNDATION_NAMESPACE_APPLY(MHFURLSessionDataTaskOperation)
    #define MHFURLSessionDownloadTaskOperation __MHFOUNDATION_NAMESPACE_APPLY(MHFURLSessionDownloadTaskOperation)
    #define MHFURLSessionTaskOperation __MHFOUNDATION_NAMESPACE_APPLY(MHFURLSessionTaskOperation)
// Categories
    #define mhf_HTTPErrorWithUserInfo __MHFOUNDATION_NAMESPACE_APPLY_LOWER(mhf_HTTPErrorWithUserInfo)
    #define mhf_JSONTaskWithSession __MHFOUNDATION_NAMESPACE_APPLY_LOWER(mhf_JSONTaskWithSession)
    #define mhf_MySQLString __MHFOUNDATION_NAMESPACE_APPLY_LOWER(mhf_MySQLString)
    #define mhf_URLSafeBase __MHFOUNDATION_NAMESPACE_APPLY_LOWER(mhf_URLSafeBase)
    #define mhf_URLWithString __MHFOUNDATION_NAMESPACE_APPLY_LOWER(mhf_URLWithString)
    #define mhf_abstractException __MHFOUNDATION_NAMESPACE_APPLY_LOWER(mhf_abstractException)
    #define mhf_addSerialOperation __MHFOUNDATION_NAMESPACE_APPLY_LOWER(mhf_addSerialOperation)
    #define mhf_allKeysSet __MHFOUNDATION_NAMESPACE_APPLY_LOWER(mhf_allKeysSet)
    #define mhf_asyncEnumerateObjectsUsingBlock __MHFOUNDATION_NAMESPACE_APPLY_LOWER(mhf_asyncEnumerateObjectsUsingBlock)
    #define mhf_cancelAllTasks __MHFOUNDATION_NAMESPACE_APPLY_LOWER(mhf_cancelAllTasks)
    #define mhf_contentEncodingGZIP __MHFOUNDATION_NAMESPACE_APPLY_LOWER(mhf_contentEncodingGZIP)
    #define mhf_dateFromMySQLString __MHFOUNDATION_NAMESPACE_APPLY_LOWER(mhf_dateFromMySQLString)
    #define mhf_dictionaryByAddingEntriesFromDictionary __MHFOUNDATION_NAMESPACE_APPLY_LOWER(mhf_dictionaryByAddingEntriesFromDictionary)
    #define mhf_errorWithDomain __MHFOUNDATION_NAMESPACE_APPLY_LOWER(mhf_errorWithDomain)
    #define mhf_fractionalMySQLString __MHFOUNDATION_NAMESPACE_APPLY_LOWER(mhf_fractionalMySQLString)
    #define mhf_isEarlierThan __MHFOUNDATION_NAMESPACE_APPLY_LOWER(mhf_isEarlierThan)
    #define mhf_isEarlierThanOrEqualTo __MHFOUNDATION_NAMESPACE_APPLY_LOWER(mhf_isEarlierThanOrEqualTo)
    #define mhf_isLaterThan __MHFOUNDATION_NAMESPACE_APPLY_LOWER(mhf_isLaterThan)
    #define mhf_isLaterThanOrEqualTo __MHFOUNDATION_NAMESPACE_APPLY_LOWER(mhf_isLaterThanOrEqualTo)
    #define mhf_isSuccessful __MHFOUNDATION_NAMESPACE_APPLY_LOWER(mhf_isSuccessful)
    #define mhf_nilIfNSNullObjectForKey __MHFOUNDATION_NAMESPACE_APPLY_LOWER(mhf_nilIfNSNullObjectForKey)
    #define mhf_notImplementedException __MHFOUNDATION_NAMESPACE_APPLY_LOWER(mhf_notImplementedException)
    #define mhf_setAcceptGzip __MHFOUNDATION_NAMESPACE_APPLY_LOWER(mhf_setAcceptGzip)
    #define mhf_setAcceptJSON __MHFOUNDATION_NAMESPACE_APPLY_LOWER(mhf_setAcceptJSON)
    #define mhf_setBasicAuthUsername __MHFOUNDATION_NAMESPACE_APPLY_LOWER(mhf_setBasicAuthUsername)
    #define mhf_setContentTypeJSON __MHFOUNDATION_NAMESPACE_APPLY_LOWER(mhf_setContentTypeJSON)
    #define mhf_setJSONObject __MHFOUNDATION_NAMESPACE_APPLY_LOWER(mhf_setJSONObject)
    #define mhf_setPOST __MHFOUNDATION_NAMESPACE_APPLY_LOWER(mhf_setPOST)
    #define mhf_setPUT __MHFOUNDATION_NAMESPACE_APPLY_LOWER(mhf_setPUT)
    #define mhf_sharedOperationQueue __MHFOUNDATION_NAMESPACE_APPLY_LOWER(mhf_sharedOperationQueue)
    #define mhf_sharedSessionMainQueue __MHFOUNDATION_NAMESPACE_APPLY_LOWER(mhf_sharedSessionMainQueue)
    #define mhf_sharedSessionMainQueueAllowInvalidSSL __MHFOUNDATION_NAMESPACE_APPLY_LOWER(mhf_sharedSessionMainQueueAllowInvalidSSL)
    #define mhf_stringTaskWithSession __MHFOUNDATION_NAMESPACE_APPLY_LOWER(mhf_stringTaskWithSession)
    #define mhf_unflattenDictionary __MHFOUNDATION_NAMESPACE_APPLY_LOWER(mhf_unflattenDictionary)
// Externs
    #define MHFHTTPErrorDomain __MHFOUNDATION_NAMESPACE_APPLY(MHFHTTPErrorDomain)
    #define MHFHTTPMethodCOPY __MHFOUNDATION_NAMESPACE_APPLY(MHFHTTPMethodCOPY)
    #define MHFHTTPMethodDELETE __MHFOUNDATION_NAMESPACE_APPLY(MHFHTTPMethodDELETE)
    #define MHFHTTPMethodGET __MHFOUNDATION_NAMESPACE_APPLY(MHFHTTPMethodGET)
    #define MHFHTTPMethodHEAD __MHFOUNDATION_NAMESPACE_APPLY(MHFHTTPMethodHEAD)
    #define MHFHTTPMethodOPTIONS __MHFOUNDATION_NAMESPACE_APPLY(MHFHTTPMethodOPTIONS)
    #define MHFHTTPMethodPATCH __MHFOUNDATION_NAMESPACE_APPLY(MHFHTTPMethodPATCH)
    #define MHFHTTPMethodPOST __MHFOUNDATION_NAMESPACE_APPLY(MHFHTTPMethodPOST)
    #define MHFHTTPMethodPUT __MHFOUNDATION_NAMESPACE_APPLY(MHFHTTPMethodPUT)
    #define MHFHTTPMethodSEARCH __MHFOUNDATION_NAMESPACE_APPLY(MHFHTTPMethodSEARCH)
    #define MHFPartialErrorsByItemIDKey __MHFOUNDATION_NAMESPACE_APPLY(MHFPartialErrorsByItemIDKey)
    #define MHFoundationErrorDomain __MHFOUNDATION_NAMESPACE_APPLY(MHFoundationErrorDomain)
#endif
